### PR TITLE
Move to Debian Stretch and some cleanups

### PR DESCRIPTION
**Pull request by chris-barry**

### CODE REVIEW

**Comment by chris-barry** [comment]
Once this is merged I am gonna sort out the automated builds

**Comment by chris-barry** [comment]
bump

**Comment by hkparker** [comment]
Whoops, sorry I missed this.  Maybe I can blame defcon.  In order to get this to build I had to add `procps` to the list of apt packages that were installed, otherwise the router complained that it could not access the command `ps`. So I appended the line `procps \` at line 38 and everything seemed good.  Are you able to reproduce?

**Comment by chris-barry** [comment]
I'll check this weekend - hope defcon was fun :D

**Comment by chris-barry** [comment]
Okay, I was able to verify what you found and am testing a bit more. I will amend the PR sometime today.

**Comment by chris-barry** [comment]
Okay, I pushed the changes. I've verified they're working. Thank you for verifying my commit :)

**Comment by hkparker** [comment]
Anytime :).  Thanks for putting the time in to keep things maintained here!  I'll get this merged, lmk if I can help with the auto-build things in any way.

**Pull request merged**
